# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Holidays-NO
version:      0.1
version_from: NO.pm
installdirs:  site
requires:
    Date::Holidays::Abstract:      0
    No::Dato:                      1.1
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
