---
name: Date-Holidays-NO
version: 0.2
author:
  - 'Marcus Ramberg, (mramberg) - E<lt>mramberg@cpan.orgE<gt>'
abstract: A wrapper for No::Dato to comply with Date::Holidays
license: perl
requires:
  Date::Holidays::Abstract: 0
  No::Dato: 1.1
  Test::More: 0
provides:
  Date::Holidays::NO:
    file: lib/Date/Holidays/NO.pm
    version: 0.2
generated_by: Module::Build version 0.2607
